name: stream_graph
description: A Dart library for constructing directed acyclic graphs of Streams building upon each other.
version: 0.2.0
publish_to: none
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  directed_graph:
  rxdart:
  freezed:


dev_dependencies:
  test: ^1.20.1
  build_runner:
