name: stream_graph
description: A Dart library for constructing directed acyclic graphs of Streams building upon each other.
repository: https://github.com/nightscape/stream_graph.dart
version: 0.3.9

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  directed_graph: ^0.3.7
  rxdart: ^0.27.3
  freezed_annotation: ^2.2.0


dev_dependencies:
  test: '<1.25.6'
  build_runner: '<2.4.10'
  freezed: 2.5.3
