name: Dart CI

# This workflow is triggered on pull requests and pushes to the repository.
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  ci:
    name: Build, format, analyze and test the package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      # Consider passing '--output=none' to 'format' for no standard output.
      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Test the package
        run: dart pub global activate coverage && dart test --coverage=coverage && format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Code Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
